import ChatFeed from "./components/ChatFeed";
import ConnectionStatus from "./components/ConnectionStatus";
import IdentityPanel from "./components/IdentityPanel";
import SentimentPanel from "./components/SentimentPanel";
import SurgePanel from "./components/SurgePanel";
import { useCrowdPulseSocket } from "./hooks/useCrowdPulseSocket";
import { useChatStore } from "./store/chatStore";

function App() {
  useCrowdPulseSocket();

  const activePlatforms = useChatStore((state) => state.activePlatforms);
  const togglePlatform = useChatStore((state) => state.togglePlatform);
  const resetPlatformFilters = useChatStore(
    (state) => state.resetPlatformFilters,
  );

  const areAllPlatformsActive = Object.values(activePlatforms).every(Boolean);

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand">
          <div className="brand__mark">CP</div>

          <div>
            <h1>CrowdPulse</h1>
            <p>One audience. Every platform. Zero noise.</p>
          </div>
        </div>

        <ConnectionStatus />
      </header>

      <main className="dashboard">
        <aside className="sidebar">
          <span className="eyebrow">Sources</span>

          <div className="source-list">
            <button
              type="button"
              className={`source-item source-item--twitch ${
                !activePlatforms.twitch ? "source-item--inactive" : ""
              }`}
              aria-pressed={activePlatforms.twitch}
              onClick={() => togglePlatform("twitch")}
            >
              <span className="source-item__dot" />
              <span>Twitch</span>
              <strong>{activePlatforms.twitch ? "Live" : "Hidden"}</strong>
            </button>

            <button
              type="button"
              className={`source-item source-item--kick ${
                !activePlatforms.kick ? "source-item--inactive" : ""
              }`}
              aria-pressed={activePlatforms.kick}
              onClick={() => togglePlatform("kick")}
            >
              <span className="source-item__dot" />
              <span>Kick</span>
              <strong>{activePlatforms.kick ? "Live" : "Hidden"}</strong>
            </button>

            <button
              type="button"
              className={`source-item source-item--x ${
                !activePlatforms.x ? "source-item--inactive" : ""
              }`}
              aria-pressed={activePlatforms.x}
              onClick={() => togglePlatform("x")}
            >
              <span className="source-item__dot" />
              <span>X</span>
              <strong>{activePlatforms.x ? "Live" : "Hidden"}</strong>
            </button>
          </div>

          <button
            type="button"
            className="source-reset-button"
            onClick={resetPlatformFilters}
            disabled={areAllPlatformsActive}
          >
            Show all platforms
          </button>

          <div className="sidebar-card">
            <span className="eyebrow">Demo adapter</span>

            <p>
              Messages are currently generated by the CrowdPulse development
              adapter.
            </p>
          </div>
        </aside>

        <ChatFeed />

        <aside className="insights-panel">
          <span className="eyebrow">Live insights</span>

          <SentimentPanel />

          <SurgePanel />

          <IdentityPanel />
        </aside>
      </main>
    </div>
  );
}

export default App;
