import ChatFeed from "./components/ChatFeed";
import ConnectionStatus from "./components/ConnectionStatus";
import IdentityPanel from "./components/IdentityPanel";
import SentimentPanel from "./components/SentimentPanel";
import SurgePanel from "./components/SurgePanel";
import { useCrowdPulseSocket } from "./hooks/useCrowdPulseSocket";

function App() {
  useCrowdPulseSocket();

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand">
          <div className="brand__mark">CP</div>

          <div>
            <h1>CrowdPulse</h1>
            <p>One audience. Every platform. Zero noise.</p>
          </div>
        </div>

        <ConnectionStatus />
      </header>

      <main className="dashboard">
        <aside className="sidebar">
          <span className="eyebrow">Sources</span>

          <div className="source-list">
            <div className="source-item source-item--twitch">
              <span className="source-item__dot" />
              <span>Twitch</span>
              <strong>Live</strong>
            </div>

            <div className="source-item source-item--kick">
              <span className="source-item__dot" />
              <span>Kick</span>
              <strong>Live</strong>
            </div>

            <div className="source-item source-item--x">
              <span className="source-item__dot" />
              <span>X</span>
              <strong>Live</strong>
            </div>
          </div>

          <div className="sidebar-card">
            <span className="eyebrow">Demo adapter</span>

            <p>
              Messages are currently generated by the CrowdPulse development
              adapter.
            </p>
          </div>
        </aside>

        <ChatFeed />

        <aside className="insights-panel">
          <span className="eyebrow">Live insights</span>

          <SentimentPanel />

          <SurgePanel />

          <IdentityPanel />
        </aside>
      </main>
    </div>
  );
}

export default App;
